version: '3.8'

services:
  backend:
    build:
      context: ./backend         
      dockerfile: Dockerfile      
    image: backend:latest         
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    name: app-network
